baseURL = "https://ahom.github.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Antoine & 张晓彤"
theme = "dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a>'

googleAnalytics = ""

disqusShortname = ""

enableRobotsTXT = true

hasCJKLanguage = false

[params]
  # background = "black"
  backgroundImage = "/me/beijing.jpg"
  linkColor = "seagreen"

  author = "Mariage"
  description = "Antoine & 张晓彤"
  avatar = "/me/food-married.jpg"
  motto = "17th May 2019, Beijing"
  

  siteStartYear = 2019

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404Button = true

[markup.goldmark.renderer]
unsafe = true
