baseURL = "https://www.antoine-et-xiaotong.com/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Antoine & Xiaotong (张晓彤)"
theme = "dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a>'

googleAnalytics = ""

disqusShortname = ""

enableRobotsTXT = true

hasCJKLanguage = true

CanonifyURLs = true

[params]
  # background = "black"
  backgroundImage = "/fr/me/beijing.jpg"
  linkColor = "seagreen"

  author = "Mariage d'Antoine et de Xiaotong (张晓彤)"
  avatar = "/me/food-married.jpg"
  motto = "29 Mai 2021, Deauville"
  

  siteStartYear = 2021

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404Button = true

[markup.goldmark.renderer]
unsafe = true
